"""Service layer: business logic extracted from cogs.

Cogs act as controllers and delegate non-trivial logic (counting, multi-step
orchestration, math) to the pure, unit-testable helpers in this package.
"""

from app.services.ai import (
    ASSISTANT_SYSTEM,
    DASHBOARD_SECTIONS,
    MODERATION_CATEGORIES,
    MUSIC_FILTERS,
    PERCY_IDENTITY,
    AIHealthReport,
    AIService,
    CommandRouter,
    EventExtractor,
    GiveawayRequest,
    ModelTier,
    ModerationAssessor,
    ModerationVerdict,
    MusicIntent,
    MusicIntentParser,
    Parsable,
    PollRequest,
    RouteCommand,
    RouteDecision,
    SchemaError,
    TagFinder,
    TagMatch,
    build_assistant_system,
    build_dashboard_assistant_system,
    build_route_system_prompt,
    build_tag_find_prompt,
    json_instruction,
)
from app.services.bot_health import (
    BotHealthReport,
    ConnectionState,
    HealthLevel,
    LavalinkMetrics,
    assess_bot_health,
    parse_lavalink_metrics,
)
from app.services.char_info import MAX_CHARACTERS, CharInfo, get_char_info
from app.services.code_stats import CodeStats, count_code_stats
from app.services.economy import (
    DailyResult,
    boost_multiplier,
    compute_daily,
    describe_effect,
    roll_lootbox,
    sell_price,
    validate_item_effect,
)
from app.services.gateway_stats import GatewayTraffic, summarize_gateway_traffic
from app.services.lyrics import LyricLine, LyricsResult, SyncedLyrics, clean_track_title, parse_lrc
from app.services.presence_stats import PRESENCE_STATUSES, PresenceBreakdown, summarize_presence
from app.services.purge import PurgeMessage, PurgePlan, build_purge_predicate
from app.services.recurrence import (
    RecurrenceResult,
    advance_recurrence,
    describe_interval,
    interval_too_short,
    next_occurrence,
    normalize_interval,
)
from app.services.spam_penalty import compute_spam_penalty

__all__ = (
    'ASSISTANT_SYSTEM',
    'DASHBOARD_SECTIONS',
    'MAX_CHARACTERS',
    'MODERATION_CATEGORIES',
    'MUSIC_FILTERS',
    'PERCY_IDENTITY',
    'PRESENCE_STATUSES',
    'AIHealthReport',
    'AIService',
    'BotHealthReport',
    'CharInfo',
    'CodeStats',
    'CommandRouter',
    'ConnectionState',
    'DailyResult',
    'EventExtractor',
    'GatewayTraffic',
    'GiveawayRequest',
    'HealthLevel',
    'LavalinkMetrics',
    'LyricLine',
    'LyricsResult',
    'ModelTier',
    'ModerationAssessor',
    'ModerationVerdict',
    'MusicIntent',
    'MusicIntentParser',
    'Parsable',
    'PollRequest',
    'PresenceBreakdown',
    'PurgeMessage',
    'PurgePlan',
    'RecurrenceResult',
    'RouteCommand',
    'RouteDecision',
    'SchemaError',
    'SyncedLyrics',
    'TagFinder',
    'TagMatch',
    'advance_recurrence',
    'assess_bot_health',
    'boost_multiplier',
    'build_assistant_system',
    'build_dashboard_assistant_system',
    'build_purge_predicate',
    'build_route_system_prompt',
    'build_tag_find_prompt',
    'clean_track_title',
    'compute_daily',
    'compute_spam_penalty',
    'count_code_stats',
    'describe_effect',
    'describe_interval',
    'get_char_info',
    'interval_too_short',
    'json_instruction',
    'next_occurrence',
    'normalize_interval',
    'parse_lavalink_metrics',
    'parse_lrc',
    'roll_lootbox',
    'sell_price',
    'summarize_gateway_traffic',
    'summarize_presence',
    'validate_item_effect',
)
