"""Service layer: business logic extracted from cogs.

Cogs act as controllers and delegate non-trivial logic (counting, multi-step
orchestration, math) to the pure, unit-testable helpers in this package.
"""

from app.services.ai import (
    ASSISTANT_SYSTEM,
    DASHBOARD_SECTIONS,
    MODERATION_CATEGORIES,
    MUSIC_FILTERS,
    PERCY_IDENTITY,
    AIHealthReport,
    AIService,
    CommandRouter,
    EventExtractor,
    GiveawayRequest,
    ModelTier,
    ModerationAssessor,
    ModerationVerdict,
    MusicIntent,
    MusicIntentParser,
    Parsable,
    PollRequest,
    RouteCommand,
    RouteDecision,
    SchemaError,
    TagFinder,
    TagMatch,
    build_assistant_system,
    build_dashboard_assistant_system,
    build_route_system_prompt,
    build_tag_find_prompt,
    json_instruction,
)
from app.services.analytics import (
    GRANULARITIES,
    METRICS,
    RANGES,
    default_granularity,
    fill_buckets,
    floor_bucket,
    resolve_granularity,
    resolve_range,
)
from app.services.backup import (
    BACKUP_KIND,
    BACKUP_VERSION,
    PORTABLE_SECTIONS,
    build_backup,
    select_sections,
    summarize_sections,
    validate_backup,
)
from app.services.bot_health import (
    BotHealthReport,
    ConnectionState,
    HealthLevel,
    LavalinkMetrics,
    assess_bot_health,
    parse_lavalink_metrics,
)
from app.services.char_info import MAX_CHARACTERS, CharInfo, get_char_info
from app.services.code_stats import CodeStats, count_code_stats
from app.services.economy import (
    DailyResult,
    EconomySnapshot,
    PeriodicResult,
    PetClaim,
    Quest,
    ShiftResult,
    boost_multiplier,
    compute_daily,
    compute_periodic,
    compute_pet_claim,
    compute_shift,
    describe_effect,
    evaluate_achievements,
    generate_daily_quests,
    get_job,
    get_species,
    pick_search_options,
    prestige_multiplier,
    prestige_requirement,
    resolve_search,
    roll_lootbox,
    sell_price,
    validate_item_effect,
)
from app.services.gateway_stats import GatewayTraffic, summarize_gateway_traffic
from app.services.lyrics import LyricLine, LyricsResult, SyncedLyrics, clean_track_title, parse_lrc
from app.services.presence_stats import PRESENCE_STATUSES, PresenceBreakdown, summarize_presence
from app.services.purge import PurgeMessage, PurgePlan, build_purge_predicate
from app.services.recurrence import (
    RecurrenceResult,
    advance_recurrence,
    describe_interval,
    interval_too_short,
    next_occurrence,
    normalize_interval,
)
from app.services.spam_penalty import compute_spam_penalty
from app.services.webhooks import (
    SIGNATURE_HEADER,
    WEBHOOK_EVENTS,
    build_envelope,
    serialize_envelope,
    sign_body,
    valid_events,
)

__all__ = (
    'ASSISTANT_SYSTEM',
    'BACKUP_KIND',
    'BACKUP_VERSION',
    'DASHBOARD_SECTIONS',
    'GRANULARITIES',
    'MAX_CHARACTERS',
    'METRICS',
    'MODERATION_CATEGORIES',
    'MUSIC_FILTERS',
    'PERCY_IDENTITY',
    'PORTABLE_SECTIONS',
    'PRESENCE_STATUSES',
    'RANGES',
    'SIGNATURE_HEADER',
    'WEBHOOK_EVENTS',
    'AIHealthReport',
    'AIService',
    'BotHealthReport',
    'CharInfo',
    'CodeStats',
    'CommandRouter',
    'ConnectionState',
    'DailyResult',
    'EconomySnapshot',
    'EventExtractor',
    'GatewayTraffic',
    'GiveawayRequest',
    'HealthLevel',
    'LavalinkMetrics',
    'LyricLine',
    'LyricsResult',
    'ModelTier',
    'ModerationAssessor',
    'ModerationVerdict',
    'MusicIntent',
    'MusicIntentParser',
    'Parsable',
    'PeriodicResult',
    'PetClaim',
    'PollRequest',
    'PresenceBreakdown',
    'PurgeMessage',
    'PurgePlan',
    'Quest',
    'RecurrenceResult',
    'RouteCommand',
    'RouteDecision',
    'SchemaError',
    'ShiftResult',
    'SyncedLyrics',
    'TagFinder',
    'TagMatch',
    'advance_recurrence',
    'assess_bot_health',
    'boost_multiplier',
    'build_assistant_system',
    'build_backup',
    'build_dashboard_assistant_system',
    'build_envelope',
    'build_purge_predicate',
    'build_route_system_prompt',
    'build_tag_find_prompt',
    'clean_track_title',
    'compute_daily',
    'compute_periodic',
    'compute_pet_claim',
    'compute_shift',
    'compute_spam_penalty',
    'count_code_stats',
    'default_granularity',
    'describe_effect',
    'describe_interval',
    'evaluate_achievements',
    'fill_buckets',
    'floor_bucket',
    'generate_daily_quests',
    'get_char_info',
    'get_job',
    'get_species',
    'interval_too_short',
    'json_instruction',
    'next_occurrence',
    'normalize_interval',
    'parse_lavalink_metrics',
    'parse_lrc',
    'pick_search_options',
    'prestige_multiplier',
    'prestige_requirement',
    'resolve_granularity',
    'resolve_range',
    'resolve_search',
    'roll_lootbox',
    'select_sections',
    'sell_price',
    'serialize_envelope',
    'sign_body',
    'summarize_gateway_traffic',
    'summarize_presence',
    'summarize_sections',
    'valid_events',
    'validate_backup',
    'validate_item_effect',
)
