version: "3"

services:
    bot:
        container_name: percy
        image: klappstuhl/percy:latest
        restart: unless-stopped

#    db:
#        container_name: percy-db
#        image: postgres
#        restart: unless-stopped
#        environment:
#            POSTGRES_DB: percy
#            POSTGRES_USER: percy
#            POSTGRES_PASSWORD: warmachine68
#        volumes:
#            - percy-db:/var/lib/postgresql/data

networks:
    bot: