services:
  snekbox:
    container_name: snekbox
    image: ghcr.io/python-discord/snekbox
    restart: unless-stopped
    ipc: none
    privileged: true
    ports:
      - "8060:8060"
    networks:
      - bot

  bot:
    container_name: percy
    build: .
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_BETA_TOKEN: ${DISCORD_BETA_TOKEN}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      LAVALINK_NODE_1_PASSWORD: ${LAVALINK_NODE_1_PASSWORD}
      STATS_WEBHOOK_TOKEN: ${STATS_WEBHOOK_TOKEN}
      GENIUS_TOKEN: ${GENIUS_TOKEN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      DBOTS_TOKEN: ${DBOTS_TOKEN}
      TOPGG_TOKEN: ${TOPGG_TOKEN}
      IMAGES_API_TOKEN: ${IMAGES_API_TOKEN}
      ANILIST_CLIENT_ID: ${ANILIST_CLIENT_ID}
      ANILIST_CLIENT_SECRET: ${ANILIST_CLIENT_SECRET}
      MARVEL_API_PUBLIC_KEY: ${MARVEL_API_PUBLIC_KEY}
      MARVEL_API_PRIVATE_KEY: ${MARVEL_API_PRIVATE_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      INTERNAL_API_TOKEN: ${INTERNAL_API_TOKEN}
      INTERNAL_API_PORT: ${INTERNAL_API_PORT:-8090}
      INTERNAL_API_HOST: "0.0.0.0"
    ports:
      - "${INTERNAL_API_PORT:-8090}:${INTERNAL_API_PORT:-8090}"
    networks:
      - bot

networks:
  bot:
    driver: bridge