import random
import re
from collections.abc import AsyncIterable, Awaitable, Callable, Coroutine
from typing import Any, ParamSpec, TypeVar

import matplotlib

P = ParamSpec('P')
T = TypeVar('T')

Coro = TypeVar('Coro', bound=Callable[..., Coroutine[Any, Any, Any]])
NCoro = TypeVar('NCoro', bound=Callable[..., Any])

type AsyncCallable[T] = Callable[P, Awaitable[T] | AsyncIterable[T]] | Callable[..., Any]
type AsyncCallableDecorator[T] = Callable[[AsyncCallable[P, T]], AsyncCallable[P, T]]

# REGEX

URL_REGEX = re.compile(r'https?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*(),]|%[0-9a-fA-F][0-9a-fA-F])+')

# DATA

COLOUR_DICT = matplotlib.colors.CSS4_COLORS | matplotlib.colors.XKCD_COLORS

GUILD_FEATURES = {
    'ANIMATED_BANNER': ('🖼️', 'Server can upload and use an animated banner.'),
    'ANIMATED_ICON': ('🌟', 'Server can upload an animated icon.'),
    'APPLICATION_permissions_V2': ('🔒', 'Server is using the new command permissions system.'),
    'AUTO_MODERATION': ('🛡️', 'Server has set up Auto Moderation.'),
    'BANNER': ('🖼️', 'Server can upload and use a banner.'),
    'COMMUNITY': ('👥', 'Server is a community server.'),
    'CREATOR_MONETIZABLE_PROVISIONAL': ('💰', 'Server is a creator server.'),
    'CREATOR_STORE_PAGE': ('🏪', 'Server has a store page.'),
    'DEVELOPER_SUPPORT_SERVER': ('👨‍💻', 'Server is a dev support server.'),
    'DISCOVERABLE': ('🔍', 'Server is discoverable.'),
    'FEATURABLE': ('🌟', 'Server is featurable.'),
    'INVITE_SPLASH': ('🌊', 'Server can upload an invite splash.'),
    'INVITES_DISABLED': ('🚫', 'Server has disabled invites.'),
    'MEMBER_VERIFICATION_GATE_ENABLED': ('✅', 'Server has enabled Membership Screening.'),
    'MONETIZATION_ENABLED': ('💰', 'Server has enabled monetization.'),
    'MORE_EMOJI': ('🔢', 'Server can upload more emojis.'),
    'MORE_STICKERS': ('🔖', 'Server can upload more stickers.'),
    'NEWS': ('📰', 'Server has set up news channels.'),
    'PARTNERED': ('🤝', 'Server is partnered.'),
    'PREVIEW_ENABLED': ('👀', 'Server has enabled preview.'),
    'ROLE_ICONS': ('👑', 'Server can set role icons.'),
    'ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE': ('💎', 'Server has purchasable role subscriptions.'),
    'ROLE_SUBSCRIPTIONS_ENABLED': ('🔑', 'Server has enabled role subscriptions.'),
    'TICKETED_EVENTS_ENABLED': ('🎟️', 'Server has enabled ticketed events.'),
    'VANITY_URL': ('🌐', 'Server has a vanity URL.'),
    'VERIFIED': ('✔️', 'Server is verified.'),
    'VIP_REGIONS': ('🎤', 'Server has VIP voice regions.'),
    'WELCOME_SCREEN_ENABLED': ('🚪', 'Server has enabled the welcome screen.')
}

WORKING_RESPONSES = [
    'Your overtime at the office pays off, and you earn {coins}.',
    'Cleaning up the local arcade machines rewards you with {coins}.',
    'Finding a lost dog and returning it to its owner earns you {coins}.',
    'Working as a barista, your perfectly crafted coffee delights customers, resulting in {coins} in tips.',
    'Helping out at a community garden earns you appreciation and {coins}.',
    'Completing gardening tasks for neighbors not only beautifies the area but also adds {coins} to your wallet.',
    'Repairing bicycles for the neighborhood kids results in {coins} as a token of gratitude.',
    'By offering tech support to elderly neighbors, you\'ve earned {coins}.',
    'Organizing a neighborhood cleanup effort not only makes the area pristine but also adds {coins} to your earnings.',
    'Your dog-walking services for busy professionals earn you {coins}.',
    'Participating in a local talent show and showcasing your skills earns you {coins} and applause.',
    'Helping out at the local animal shelter not only warms your heart but also adds {coins} to your pocket.',
    'By offering your services as a personal shopper, you\'ve earned {coins}.',
    'Your efforts in assisting a local business with social media management result in {coins}.',
    'Completing handyman tasks for neighbors has earned you {coins}.',
    'Working as a lifeguard for a community pool results in {coins} for your watchful eyes.',
    'Creating and selling artwork online brings in {coins} from art enthusiasts.',
    'Assisting someone in moving their furniture proves physically demanding but rewarding with {coins}.',
    'Participating in a local singing competition not only showcases your talent but also earns you {coins}.',
    'Helping organize a local charity run earns you gratitude and {coins}.',
    'Providing gardening services to local businesses results in {coins}.',
    'Completing a freelance writing assignment on sustainable living earns you {coins}.',
    'By offering your skills as a private tutor, you\'ve earned {coins}.',
    'Participating in a focus group on consumer products has added {coins} to your account.',
    'Helping a neighbor set up their new smart home devices has earned you {coins}.',
    'By organizing and hosting a neighborhood movie night, you\'ve earned {coins}.',
    'Completing odd jobs for neighbors, such as fixing leaky faucets and painting fences, has earned you {coins}.',
    'Offering fitness coaching services to local residents has earned you {coins}.',
    'Participating in a community book club not only expands your literary horizons but also earns you {coins}.',
    'Helping organize a local food drive for the less fortunate has earned you {coins}.',
    'By offering your photography skills for local events, you\'ve earned {coins}.',
    'Your efforts in finding lost items for neighbors have been rewarded with {coins}.',
    'Assisting with event planning for local celebrations has earned you {coins}.',
    'Participating in a neighborhood chess tournament not only hones your skills but also earns you {coins}.',
    'By offering your skills as a language tutor, you\'ve earned {coins}.',
    'Helping set up and decorate for local celebrations has earned you {coins}.',
    'Completing a freelance graphic design project for a local business has earned you {coins}.',
    'Participating in a local cooking competition not only showcases your culinary talents but also earns you {coins}.',
    'Your efforts in helping a neighbor with computer issues have earned you {coins}.',
    'By offering your skills as a music instructor, you\'ve earned {coins}.',
    'Organizing a local gaming night has not only brought joy to gamers but also earned you {coins}.',
    'Helping out at a local farm has not only connected you with nature but also earned you {coins}.',
    'Completing a freelance programming project for a local startup has earned you {coins}.',
    'By offering your skills as a dance instructor, you\'ve earned {coins}.',
    'Participating in a community theater production not only entertains but also earns you {coins}.',
    'Your efforts in helping a local business with social media marketing have earned you {coins}.',
    'Assisting a neighbor with home repairs has earned you {coins}.',
    'By offering your skills as a yoga instructor, you\'ve earned {coins}.',
    'Participating in a neighborhood photography contest not only showcases your talent but also earns you {coins}.',
    'Your efforts in helping a local community center with event planning have earned you {coins}.',
    'Assisting a neighbor with setting up a home office has earned you {coins}.',
    'By offering your skills as a personal trainer, you\'ve earned {coins}.',
    'Participating in a local art exhibition not only showcases your creativity but also earns you {coins}.',
    'Helping a neighbor organize a garage sale has not only decluttered spaces but also earned you {coins}.',
    'Completing freelance writing assignments for local businesses has earned you {coins}.',
    'By offering your skills as a coding tutor, you\'ve earned {coins}.',
    'Participating in a neighborhood astronomy night not only stargazes but also earns you {coins}.',
    'Your efforts in helping a local school with educational workshops have earned you {coins}.',
    'Assisting a neighbor with gardening has not only cultivated plants but also earned you {coins}.',
    'Completing a freelance web development project for a local client has earned you {coins}.',
    'By offering your skills as a language translator, you\'ve earned {coins}.',
    'Participating in a community fitness challenge not only promotes health but also earns you {coins}.',
    'Your efforts in helping a local animal rescue with social media promotion have earned you {coins}.',
    'Assisting a neighbor with setting up a home gym has earned you {coins}.',
    'By offering your skills as a cooking instructor, you\'ve earned {coins}.',
    'Participating in a local bird-watching event not only appreciates nature but also earns you {coins}.',
    'Helping a neighbor organize a DIY workshop has not only fostered creativity but also earned you {coins}.',
    'Completing freelance graphic design projects for local musicians has earned you {coins}.',
    'By offering your skills as a math tutor, you\'ve earned {coins}.',
    'Participating in a neighborhood gardening club not only cultivates plants but also earns you {coins}.',
    'Your efforts in helping a local community center with tech workshops have earned you {coins}.',
    'Assisting a neighbor with setting up a home art studio has earned you {coins}.',
    'Completing a freelance marketing project for a local business has earned you {coins}.',
    'By offering your skills as a dance choreographer, you\'ve earned {coins}.',
    'Participating in a local poetry slam not only expresses creativity but also earns you {coins}.',
    'Your efforts in helping a local library with reading programs have earned you {coins}.',
    'Assisting a neighbor with setting up a home music studio has earned you {coins}.',
    'Completing freelance writing assignments for local magazines has earned you {coins}.',
    'By offering your skills as a coding consultant, you\'ve earned {coins}.',
    'Participating in a neighborhood hiking group not only promotes fitness but also earns you {coins}.',
    'Your efforts in helping a local youth center with after-school programs have earned you {coins}.',
    'Assisting a neighbor with setting up a home workshop has earned you {coins}.',
    'Completing a freelance illustration project for a local author has earned you {coins}.',
    'By offering your skills as a language interpreter, you\'ve earned {coins}.',
    'Participating in a community environmental cleanup not only helps the planet but also earns you {coins}.',
    'Your efforts in helping a local tech club with coding workshops have earned you {coins}.',
    'Assisting a neighbor with setting up a home science lab has earned you {coins}.',
    'Completing freelance video editing projects for local content creators has earned you {coins}.',
    'By offering your skills as a math problem solver, you\'ve earned {coins}.',
    'Participating in a neighborhood astronomy club not only explores the cosmos but also earns you {coins}.',
    'Your efforts in helping a local community center with art programs have earned you {coins}.',
    'Assisting a neighbor with setting up a home podcast studio has earned you {coins}.',
    'Completing freelance social media management for local businesses has earned you {coins}.',
    'By offering your skills as a dance fitness instructor, you\'ve earned {coins}.',
    'Participating in a local film festival not only celebrates cinema but also earns you {coins}.',
    'Your efforts in helping a local animal shelter with adoption events have earned you {coins}.',
    'Assisting a neighbor with setting up a home theater has earned you {coins}.',
    'Completing a freelance content writing project for a local startup has earned you {coins}.',
    'By offering your skills as a coding mentor, you\'ve earned {coins}.',
    'Participating in a community sports league not only fosters teamwork but also earns you {coins}.',
    'Your efforts in helping a local literacy program with reading sessions have earned you {coins}.',
    'Assisting a neighbor with setting up a home photography studio has earned you {coins}.',
    'Completing freelance web development projects for local nonprofits has earned you {coins}.',
    'By offering your skills as a language tutor, you\'ve earned {coins}.',
    'Participating in a neighborhood fitness challenge not only promotes health but also earns you {coins}.',
    'Your efforts in helping a local community garden with planting have earned you {coins}.',
    'Assisting a neighbor with setting up a home office has earned you {coins}.',
    'Completing a freelance marketing project for a local business has earned you {coins}.',
    'By offering your skills as a dance choreographer, you\'ve earned {coins}.',
    'Participating in a local poetry slam not only expresses creativity but also earns you {coins}.',
    'Your efforts in helping a local library with reading programs have earned you {coins}.',
    'Assisting a neighbor with setting up a home music studio has earned you {coins}.',
    'Completing freelance writing assignments for local magazines has earned you {coins}.',
    'By offering your skills as a coding consultant, you\'ve earned {coins}.',
    'Participating in a neighborhood hiking group not only promotes fitness but also earns you {coins}.',
    'Your efforts in helping a local youth center with after-school programs have earned you {coins}.',
    'Assisting a neighbor with setting up a home workshop has earned you {coins}.',
    'Completing a freelance illustration project for a local author has earned you {coins}.',
    'By offering your skills as a language interpreter, you\'ve earned {coins}.',
    'Participating in a community environmental cleanup not only helps the planet but also earns you {coins}.',
    'Your efforts in helping a local tech club with coding workshops have earned you {coins}.',
    'Assisting a neighbor with setting up a home science lab has earned you {coins}.',
    'Completing freelance video editing projects for local content creators has earned you {coins}.',
    'By offering your skills as a math problem solver, you\'ve earned {coins}.',
    'Participating in a neighborhood astronomy club not only explores the cosmos but also earns you {coins}.',
    'Your efforts in helping a local community center with art programs have earned you {coins}.',
    'Assisting a neighbor with setting up a home podcast studio has earned you {coins}.',
    'Completing freelance social media management for local businesses has earned you {coins}.',
    'By offering your skills as a dance fitness instructor, you\'ve earned {coins}.',
    'Participating in a local film festival not only celebrates cinema but also earns you {coins}.',
    'Your efforts in helping a local animal shelter with adoption events have earned you {coins}.',
    'Assisting a neighbor with setting up a home theater has earned you {coins}.',
    'Completing a freelance content writing project for a local startup has earned you {coins}.',
    'By offering your skills as a coding mentor, you\'ve earned {coins}.',
    'Participating in a community sports league not only fosters teamwork but also earns you {coins}.',
    'Your efforts in helping a local literacy program with reading sessions have earned you {coins}.',
    'Assisting a neighbor with setting up a home photography studio has earned you {coins}.',
    'Completing freelance web development projects for local nonprofits has earned you {coins}.',
    'By offering your skills as a language tutor, you\'ve earned {coins}.',
    'Participating in a neighborhood fitness challenge not only promotes health but also earns you {coins}.',
    'Your efforts in helping a local community garden with planting have earned you {coins}.',
    'Assisting a neighbor with setting up a home office has earned you {coins}.',
    'Completing a freelance marketing project for a local business has earned you {coins}.',
    'By offering your skills as a dance choreographer, you\'ve earned {coins}.',
    'Participating in a local poetry slam not only expresses creativity but also earns you {coins}.',
    'Your efforts in helping a local library with reading programs have earned you {coins}.',
    'Assisting a neighbor with setting up a home music studio has earned you {coins}.',
    'Completing freelance writing assignments for local magazines has earned you {coins}.',
    'By offering your skills as a coding consultant, you\'ve earned {coins}.',
    'Participating in a neighborhood hiking group not only promotes fitness but also earns you {coins}.',
    'Your efforts in helping a local youth center with after-school programs have earned you {coins}.',
    'Assisting a neighbor with setting up a home workshop has earned you {coins}.',
    'Completing a freelance illustration project for a local author has earned you {coins}.',
    'By offering your skills as a language interpreter, you\'ve earned {coins}.',
]

SUCCESSFULL_CRIME_RESPONSES = [
    'Successfully hacking into a corporation\'s database, you transfer {coins} into your account.',
    'Pickpocketing a bystander in a crowded area, you gain {coins}.',
    'With stealthy precision, you break into a bank vault and escape with {coins}.',
    'Embracing your inner cat burglar, you successfully steal a rare artifact worth {coins}.',
    'Masterfully orchestrating a heist, you make a clean getaway with {coins}.',
    'Discreetly shoplifting valuable items, you pocket {coins} without getting caught.',
    'Breaking into a wealthy home, you make off with valuable possessions worth {coins}.',
    'Successfully cracking a high-security safe, you find {coins} inside.',
    'Pilfering goods from a black-market dealer, you make a quick escape with {coins}.',
    'Conning a gullible mark, you walk away with {coins} in ill-gotten gains.',
    'Infiltrating an exclusive party, you lift valuable items worth {coins}.',
    'Successfully swindling a casino, you leave with {coins} in your pocket.',
    'Extorting a local business, you collect {coins} in protection money.',
    'Successfully counterfeiting currency, you exchange fake bills for {coins}.',
    'Robbing an armored car, you escape with {coins} before the authorities arrive.',
    'Kidnapping a wealthy individual, you receive a ransom of {coins}.',
    'Successfully looting an electronics store, you fence the goods for {coins}.',
    'Cracking a high-stakes poker game, you walk away with {coins} in winnings.',
    'Bribing a security guard, you gain access to a high-value target and steal {coins}.',
    'Successfully hijacking a delivery truck, you make off with {coins} worth of merchandise.',
    'Successfully infiltrating a museum, you steal priceless artifacts worth {coins}.',
    'Fraudulently obtaining credit card information, you make unauthorized purchases totaling {coins}.',
    'Successfully hacking into government records, you blackmail officials and receive {coins}.',
    'Bypassing security systems, you break into a luxury car showroom and steal a vehicle worth {coins}.',
    'Successfully conducting an insider trading scheme, you profit {coins} from the stock market.',
    'Evading security, you successfully shoplift luxury items worth {coins}.',
    'Selling stolen identities on the dark web, you earn {coins} from illicit transactions.',
    'Successfully infiltrating a high-end jewelry store, you steal gems worth {coins}.',
    'Ransacking a wealthy residence, you find valuable heirlooms and make off with {coins}.',
    'Successfully robbing a high-stakes poker game, you leave with {coins} in winnings.',
    'Breaking into an exclusive art gallery, you steal a valuable painting worth {coins}.',
    'Successfully hacking into a cryptocurrency exchange, you transfer {coins} to your account.',
    'Disguised as a janitor, you successfully infiltrate a government facility and steal classified documents worth {coins}.',
    'Successfully manipulating the outcome of a horse race, you earn {coins} from your bets.',
    'Successfully infiltrating a high-security laboratory, you steal experimental technology worth {coins}.',
    'Successfully sabotaging a competitor\'s business, you profit {coins} from their downfall.',
    'Successfully smuggling contraband across borders, you make {coins} from illicit trade.',
    'Successfully blackmailing a prominent figure, you receive a hefty sum of {coins}.',
    'Successfully tampering with a casino\'s slot machines, you leave with {coins} in winnings.',
    'Successfully organizing an elaborate heist, you make a dramatic escape with {coins}.',
    'Successfully manipulating the stock market, you profit {coins} from your strategic trades.',
    'Successfully conducting a cyber attack on a major corporation, you extort {coins} from them.',
    'Successfully infiltrating a high-profile event, you make off with {coins} worth of valuables.',
    'Successfully sabotaging a rival gang\'s operation, you seize control and earn {coins}.',
    'Successfully infiltrating a high-security auction, you steal a priceless artifact worth {coins}.',
    'Impersonating a wealthy individual, you successfully embezzle {coins} from unsuspecting investors.',
    'Successfully extorting a corrupt official, you receive a substantial payoff of {coins}.',
    'Infiltrating a celebrity\'s mansion, you make off with valuable items worth {coins}.',
    'Successfully tampering with a horse race, you profit {coins} from your strategic bets.',
    'Craftily manipulating a jury, you successfully acquit yourself of all charges, preserving your {coins}.',
    'Sneakily manipulating the art market, you sell forgeries and earn {coins}.',
    'Successfully stealing a rare gem from a high-security vault, you pocket {coins}.',
    'Bribing a key witness, you successfully avoid criminal charges and keep your {coins}.',
    'Fooling security systems, you successfully break into a high-end boutique and steal designer items worth {coins}.',
    'Successfully orchestrating a jewelry store heist, you escape with gems worth {coins}.',
    'Successfully blackmailing a powerful figure, you receive a substantial payoff of {coins}.',
    'Infiltrating a government auction, you steal classified documents and earn {coins} from selling them.',
    'Successfully hacking into a cryptocurrency exchange, you transfer {coins} to your account.',
    'Smoothly conning a casino, you leave with {coins} in your pocket.',
    'Successfully manipulating the outcome of a political election, you receive {coins} for your influence.',
    'Falsifying evidence, you successfully frame a rival gang and earn {coins} from the chaos.',
    'Successfully hijacking a luxury yacht, you make off with {coins} worth of valuables.',
    'Infiltrating a high-end fashion event, you steal designer outfits worth {coins}.',
    'Successfully extorting a rival gang, you receive a hefty payout of {coins}.',
    'Manipulating a jury, you successfully acquit yourself of all charges, preserving your {coins}.',
    'Masterfully infiltrating a high-security gala, you steal a rare painting worth {coins}.',
    'Successfully sabotaging a business competitor, you profit {coins} from their downfall.',
    'Escaping from prison, you successfully evade authorities and keep your {coins}.',
    'Fooling facial recognition systems, you successfully replace a high-profile individual, extorting {coins} in the process.',
    'Successfully orchestrating a massive data breach, you sell sensitive information for {coins}.',
    'Successfully stealing a rare artifact from a museum, you receive a reward of {coins} from a mysterious buyer.',
    'Successfully manipulating the stock market, you profit {coins} from your strategic trades.',
    'Craftily infiltrating a high-security laboratory, you steal experimental technology worth {coins}.',
    'Masterfully disguising yourself as a police officer, you successfully infiltrate a crime scene and steal evidence worth {coins}.',
    'Successfully conducting an elaborate Ponzi scheme, you walk away with {coins} in ill-gotten gains.',
    'Smoothly infiltrating a private club, you make off with {coins} worth of valuables.',
    'Successfully hacking into a government server, you blackmail officials and receive {coins}.',
    'Masterfully organizing a massive heist, you escape with {coins} in a daring getaway.',
    'Successfully manipulating the outcome of a sports event, you profit {coins} from your bets.',
    'Falsifying your own death, you successfully escape legal consequences and preserve your {coins}.',
    'Successfully infiltrating a secret society, you steal ancient artifacts worth {coins}.',
    'Smoothly manipulating a jury, you successfully acquit yourself of all charges, preserving your {coins}.',
    'Masterfully conning a high-profile mark, you walk away with {coins} in ill-gotten gains.',
    'Successfully orchestrating a massive casino heist, you leave with {coins} in a dazzling escape.',
    'Smoothly manipulating a jury, you successfully acquit yourself of all charges, preserving your {coins}.',
    'Masterfully infiltrating a government facility, you steal classified documents worth {coins}.',
    'Successfully conning a corrupt politician, you receive a substantial payoff of {coins}.',
    'Fooling security systems, you successfully break into a high-end technology company and steal prototypes worth {coins}.',
    'Successfully blackmailing a powerful figure, you receive a hefty payoff of {coins}.',
]

FAILED_CRIME_RESPONSES = [
    'Attempting to hack into a corporation\'s database, you trigger an alarm, resulting in a {coins} fine.',
    'Caught red-handed while pickpocketing, a vigilant NPC forces you to pay a fine of {coins}.',
    'Breaking into a bank vault, an alarm is triggered, and authorities catch you. You face a fine of {coins}.',
    'Your cat burglary attempt goes awry, and you\'re apprehended with the stolen artifact. Fine: {coins} awaits.',
    'Security thwarts your ambitious heist, leading to a {coins} fine for trespassing.',
    'Shoplifting goes wrong as security apprehends you, resulting in a {coins} fine.',
    'Breaking into a wealthy home, the residents catch you in the act, and you face a fine of {coins}.',
    'Attempting to crack a high-security safe, an alarm is triggered, and you\'re caught. Fine: {coins}.',
    'Pilfering goods from a black-market dealer attracts undercover officers, leading to a {coins} fine.',
    'Your con job backfires as your gullible mark turns out to be an undercover agent. Fine: {coins}.',
    'Infiltrating an exclusive party, you\'re recognized and detained by security, facing a {coins} fine.',
    'Your attempt to swindle a casino results in security detaining you, and you\'re fined {coins}.',
    'Extorting a local business attracts the attention of authorities, resulting in a {coins} fine.',
    'Your counterfeit currency is detected, and you\'re fined {coins} for your actions.',
    'Attempting to rob an armored car, you\'re caught in the act by the police, facing a {coins} fine.',
    'Kidnapping goes wrong as law enforcement intervenes, and you\'re fined {coins}.',
    'Looting an electronics store results in your arrest, and you\'re fined {coins}.',
    'Cracking a poker game results in the casino pressing charges, and you\'re fined {coins}.',
    'Attempting to bribe a security guard leads to your arrest, accompanied by a {coins} fine.',
    'Hijacking a delivery truck is foiled, and you\'re caught by the police. Fine: {coins}.',
    'Infiltrating a museum results in your arrest for stealing artifacts. You face a {coins} fine.',
    'Fraudulently obtaining credit card information leads to your arrest, and you\'re fined {coins}.',
    'Attempting to hack into government records attracts the attention of law enforcement, resulting in a {coins} fine.',
    'Bypassing security to steal a car ends with your arrest, and you\'re fined {coins}.',
    'Insider trading results in legal consequences, and you\'re fined {coins}.',
    'Shoplifting luxury items results in your arrest, and you\'re fined {coins}.',
    'Selling stolen identities leads to your arrest, accompanied by a {coins} fine.',
    'Infiltrating a high-end jewelry store results in your arrest, and you face a {coins} fine.',
    'Ransacking a wealthy residence ends with your arrest, and you\'re fined {coins}.',
    'Attempting to rob a poker game results in your arrest, and you\'re fined {coins}.',
    'Breaking into an art gallery ends with your arrest, and you face a {coins} fine.',
    'Hacking into a cryptocurrency exchange results in legal consequences, and you\'re fined {coins}.',
    'Attempting to infiltrate a government facility results in your arrest. You face a {coins} fine.',
    'Manipulating a horse race is exposed, and you face legal consequences. Fine: {coins}.',
    'Infiltrating a high-security laboratory results in your arrest, and you\'re fined {coins}.',
    'Sabotaging a competitor\'s business attracts legal consequences, and you\'re fined {coins}.',
    'Smuggling contraband across borders results in your arrest, and you\'re fined {coins}.',
    'Blackmailing a prominent figure leads to legal consequences, and you\'re fined {coins}.',
    'Tampering with casino slot machines results in your arrest. You face a {coins} fine.',
    'Your elaborate heist is foiled, and you\'re apprehended, accompanied by a {coins} fine.',
    'Manipulating the stock market leads to legal consequences, and you\'re fined {coins}.',
    'Conducting a cyber attack on a major corporation results in legal consequences, and you\'re fined {coins}.',
    'Infiltrating a high-profile event results in your arrest. You face a {coins} fine.',
    'Sabotaging a rival gang\'s operation goes wrong, and you\'re caught. Fine: {coins}.',
    'Attempting to infiltrate a high-security auction, you are caught, and your heist ends with a {coins} fine.',
    'Impersonating a wealthy individual, you\'re exposed, and investors demand restitution, resulting in a {coins} fine.',
    'Your attempt to extort a corrupt official goes wrong, and you\'re fined {coins} for your actions.',
    'Infiltrating a celebrity\'s mansion, you\'re caught by security, resulting in a {coins} fine.',
    'Tampering with a horse race backfires, and you lose {coins} in failed bets.',
    'Attempting to manipulate a jury, your plan unravels, leading to legal consequences and a {coins} fine.',
    'Manipulating the art market results in exposure, and you\'re fined {coins} for your forgeries.',
    'Breaking into a high-security vault, an alarm is triggered, and authorities catch you. You face a {coins} fine.',
    'Bribing a key witness backfires, leading to your arrest and a {coins} fine.',
    'Breaking into a high-end boutique, you\'re caught by security, resulting in a {coins} fine.',
    'Orchestrating a jewelry store heist attracts the attention of the police, resulting in a {coins} fine.',
    'Blackmailing a powerful figure goes wrong, and you\'re fined {coins} for your actions.',
    'Infiltrating a government auction results in your arrest for stealing classified documents. Fine: {coins}.',
    'Hacking into a cryptocurrency exchange results in exposure, legal consequences, and a {coins} fine.',
    'Conning a casino leads to security detaining you, and you\'re fined {coins}.',
    'Manipulating a political election results in exposure, legal consequences, and a {coins} fine.',
    'Falsifying evidence leads to your arrest, and you\'re fined {coins} for your actions.',
    'Hijacking a luxury yacht is foiled, and you\'re caught by the police. Fine: {coins}.',
    'Infiltrating a high-end fashion event results in your arrest for stealing designer outfits. Fine: {coins}.',
    'Extorting a rival gang goes wrong, and you\'re fined {coins} for your actions.',
    'Manipulating a jury backfires, and you\'re fined {coins} for your actions.',
    'Infiltrating a high-security gala results in your arrest for stealing a rare painting. Fine: {coins}.',
    'Sabotaging a business competitor attracts legal consequences, and you\'re fined {coins}.',
    'Escaping from prison results in your re-arrest, and you\'re fined {coins}.',
    'Fooling facial recognition systems goes wrong, and you\'re fined {coins} for your actions.',
    'Orchestrating a massive data breach results in exposure, legal consequences, and a {coins} fine.',
    'Stealing a rare artifact from a museum leads to your arrest, and you\'re fined {coins}.',
    'Manipulating the stock market leads to exposure, legal consequences, and a {coins} fine.',
    'Infiltrating a high-security laboratory results in your arrest for stealing experimental technology. Fine: {coins}.',
    'Disguising yourself as a police officer goes wrong, leading to your arrest and a {coins} fine.',
    'Conducting an elaborate Ponzi scheme leads to your arrest, and you\'re fined {coins}.',
    'Infiltrating a private club results in your arrest for theft. Fine: {coins}.',
    'Hacking into a government server leads to exposure, legal consequences, and a {coins} fine.',
    'Organizing a massive heist goes wrong, and you\'re caught by authorities. Fine: {coins}.',
    'Manipulating the outcome of a sports event results in exposure, legal consequences, and a {coins} fine.',
    'Falsifying your own death attracts legal consequences, and you\'re fined {coins}.',
    'Infiltrating a secret society results in exposure, legal consequences, and a {coins} fine.',
    'Manipulating a jury backfires, and you\'re fined {coins} for your actions.',
    'Conning a high-profile mark results in exposure, legal consequences, and a {coins} fine.',
    'Orchestrating a massive casino heist goes wrong, and you\'re caught by security. Fine: {coins}.',
    'Manipulating a jury backfires, and you\'re fined {coins} for your actions.',
    'Infiltrating a government facility results in your arrest for stealing classified documents. Fine: {coins}.',
    'Conning a corrupt politician goes wrong, and you\'re fined {coins} for your actions.',
    'Breaking into a high-end technology company attracts legal consequences, and you\'re fined {coins}.',
    'Blackmailing a powerful figure goes wrong, and you\'re fined {coins} for your actions.',
]

SUCCESSFULL_SLUT_RESPONSES = [
    'After a wild night at the club, you find yourself in the middle of a steamy orgy, earning {coins} and a sense of euphoria.',
    'You engage in a passionate encounter with a mysterious stranger, resulting in a night of pleasure and {coins}.',
    'During a risqué performance, you captivate a wealthy patron who rewards you generously with {coins} for a private rendezvous.',
    'You attend a lavish masquerade ball and indulge in a sinful tryst with a masked stranger, earning {coins} and a thrilling memory.',
    'After a seductive dance, you catch the eye of a powerful noble who offers you a generous payment of {coins} for a night of pleasure.',
    'You participate in a secret underground event where desires run wild, and you earn {coins} for your uninhibited participation.',
    'A high-profile client invites you to a luxury yacht party where you engage in a scandalous affair, earning {coins} and a taste of the high life.',
    'You join a group of like-minded individuals for a night of debauchery, resulting in a memorable orgy and {coins} as a reward.',
    'After downing a few shots, you find yourself in a passionate encounter with the barmaid. Somehow, you end up with {coins} and a real sore hangover.',
    'You become the center of attention at an exclusive swingers\' party, indulging in various encounters and collecting {coins} for your services.',
    'During a heated encounter with a wealthy benefactor, you leave a lasting impression and receive {coins} as a token of appreciation.',
    'In a daring act of seduction, you engage in a thrilling threesome, earning {coins} and unforgettable memories.',
    'You attend an elite BDSM club and captivate a dominatrix who rewards you with {coins} for your submission.',
    'After an intense workout session, you find yourself in a steamy encounter with your personal trainer, gaining {coins} and a new level of physical satisfaction.',
    'During a weekend getaway, you engage in a passionate affair with a stranger, earning {coins} and a secret to cherish.',
    'An influential politician becomes infatuated with you and offers a substantial sum of {coins} for a discreet affair.',
    'You join a secret society dedicated to pleasure, where you engage in a night of sinful indulgence and earn {coins} for your participation.',
    'After a provocative photo shoot, you catch the attention of a wealthy collector who commissions an intimate session, rewarding you with {coins}.',
    'In a daring act of exhibitionism, you engage in a steamy encounter in a public place, earning {coins} and an adrenaline rush.',
    'You become a muse for a talented artist who pays you handsomely with {coins} for your intimate inspiration.',
    'During a trip to a tropical paradise, you find yourself in a passionate tryst with a fellow vacationer, earning {coins} and unforgettable memories.',
    'After a sensual dance performance, you captivate a wealthy patron who offers a generous payment of {coins} for a private show.',
    'You engage in a thrilling encounter with a powerful crime lord, earning {coins} and a dangerous reputation.',
    'In a secret underground club, you participate in an extravagant orgy, earning {coins} and a reputation as a hedonistic pleasure-seeker.',
    'After a chance encounter at a masked ball, you engage in a night of uninhibited passion, earning {coins} and a sense of liberation.',
    'You become the object of desire for a group of wealthy individuals, indulging in a night of extravagant pleasure and earning {coins} as a reward.',
    'After a steamy encounter in a luxurious penthouse, a wealthy entrepreneur rewards you with a generous payment of {coins} for your services.',
    'You join a private fetish party, exploring your darkest desires and earning {coins} for your willingness to indulge.',
    'In a daring act of voyeurism, you engage in a passionate encounter while others watch, earning {coins} and a thrill like no other.',
    'You attend an exclusive sex club where you engage in a night of uninhibited pleasure, collecting {coins} as a reward for your participation.',
    'After an intense flirtation, you find yourself in a passionate encounter with a powerful CEO, earning {coins} and a newfound level of influence.',
    'After a night of heavy drinking, you find yourself in the middle of a wild orgy. You wake up with {coins} and a satisfied smile.',
    'You engage in a steamy encounter with a wealthy aristocrat, earning {coins} and a reputation as an insatiable lover.',
    'In a daring act of seduction, you entice a group of influential individuals into a night of pleasure. You leave with {coins} and a sense of power.',
    'You become the centerpiece of a hedonistic party, indulging in every desire imaginable. In the end, you walk away with {coins} and a euphoric high.',
    'After an intimate encounter with a powerful crime lord, you receive a handsome payment of {coins} and a taste of danger.',
    'You join a secret society dedicated to pleasure, engaging in an unforgettable night of ecstasy. They reward you with {coins} and a newfound sense of belonging.',
    'In a forbidden affair with a married couple, you discover the thrill of unconventional love. They shower you with {coins} as a token of their appreciation.',
    'After a passionate encounter with a mysterious stranger, you find yourself richer by {coins} and haunted by their lingering touch.',
    'You offer your services to a group of high-ranking officials, fulfilling their deepest desires. In return, they reward you generously with {coins}.',
    'Under the influence of an aphrodisiac, you engage in a wild night of pleasure with multiple partners. You wake up with {coins} and a naughty secret.',
    'During a yacht party, you catch the eye of a billionaire who offers you a night of pleasure in exchange for {coins}.',
    'In a lavish penthouse suite, you engage in a passionate threesome with a famous celebrity couple, earning {coins} and a taste of the glamorous life.',
    'After an intense workout at the gym, you join a group of fitness enthusiasts for a sweaty and exhilarating sexual escapade, receiving {coins} as a reward.',
    'In a luxurious hotel suite, you become the plaything of a wealthy socialite, receiving {coins} and lavish gifts as a token of appreciation.',
    'At an exclusive swingers club, you explore your wildest fantasies with like-minded individuals, earning {coins} and a sense of liberation.',
    'During a visit to a renowned sex club, you engage in a thrilling foursome, leaving with {coins} and unforgettable memories.',
    'In a dimly lit bar, you attract the attention of a seductive stranger who takes you to a private room for a night of passion, earning {coins} and a sense of adventure.',
    'After a provocative performance at a cabaret, you are invited backstage to join the sensual cast in an intoxicating orgy, receiving {coins} as a token of appreciation.',
    'In a secret underground society, you participate in a masked orgy, indulging in forbidden pleasures and receiving {coins} as a reward.',
    'After a night of dancing at a decadent nightclub, you find yourself in a passionate encounter with a mysterious stranger, earning {coins} and a sense of intrigue.',
    'In a hidden garden, you join a secret society dedicated to hedonism, engaging in a sensual orgy and receiving {coins} as a symbol of your membership.',
    'After a daring strip poker game, you engage in a wild group encounter with the other players, leaving with {coins} and a devilish grin.',
    'In a secluded mansion, you are initiated into a secret society of pleasure-seekers, indulging in a passionate orgy and receiving {coins} as a mark of your acceptance.',
    'After a flirtatious encounter at a masked ball, you engage in a steamy threesome with a captivating couple, earning {coins} and a sense of satisfaction.',
]

FAILED_SLUT_RESPONSES = [
    'After indulging in a steamy affair with a wealthy client, you wake up to find {coins} missing from your pocket.',
    'You engage in a wild night of passion with a stranger, only to discover {coins} mysteriously gone from your stash.',
    'After a reckless encounter with a group of strangers, you realize {coins} have been discreetly taken from your possession.',
    'In a secret underground club, you become a part of an intense orgy and later find {coins} missing from your wallet.',
    'During a wild party, you engage in a group sex session and later realize {coins} have been stolen from your purse.',
    'After a flirtatious encounter at the casino, you join a high-stakes poker game that ends in a scandalous sexcapade, resulting in {coins} being swindled from you.',
    'During a masquerade ball, you have a passionate encounter with a masked stranger, waking up to find {coins} mysteriously vanished.',
    'You become the center of attention at a decadent sex party, indulging in various acts of pleasure, but discover {coins} missing from your earnings.',
    'At an exclusive BDSM event, you become the submissive of a skilled Dom, who cunningly takes {coins} from your pocket as punishment.',
    'In a secluded cabin, you have a passionate tryst with a rugged woodsman, only to realize {coins} have been pilfered from your belongings.',
    'During a weekend getaway, you become the object of desire for an entire group, resulting in a euphoric orgy, but leaving you with {coins} missing as a result.',
    'After a provocative performance at a burlesque club, you engage in a backstage rendezvous, but discover {coins} discreetly stolen from your purse.',
    'Under the moonlight, you join a secret society dedicated to pleasure, indulging in an unforgettable orgy, but finding {coins} missing from your stash.',
    'After a steamy encounter with a powerful politician, you receive a generous payment of {coins}, only to have it forcibly taken back.',
    'In a hidden dungeon, you explore the world of BDSM with a skilled Master, who cunningly swindles {coins} from your possession.',
    'During a yacht party, you catch the eye of a billionaire who offers you a night of pleasure in exchange for {coins}, but ends up taking more than agreed upon.',
    'In a lavish penthouse suite, you have a passionate threesome with a famous celebrity couple, but discover {coins} missing from your wallet.',
    'After an intense workout at the gym, you join a group of fitness enthusiasts for a sweaty and exhilarating sexual escapade, but find {coins} mysteriously gone.',
    'In a luxurious hotel suite, you become the plaything of a wealthy socialite, who cunningly takes {coins} from your purse as a gesture of dominance.',
    'At an exclusive swingers club, you explore your wildest fantasies with like-minded individuals, but end up losing {coins} in the process.',
    'During a visit to a renowned sex club, you engage in a thrilling foursome, but realize {coins} have been stolen from your clothing.',
    'In a dimly lit bar, you attract the attention of a seductive stranger who takes you to a private room for a night of pleasure, leaving you with {coins} missing from your pocket.',
    'After a provocative performance at a cabaret, you are invited backstage to join the sensual cast in an intoxicating orgy, but find {coins} discreetly taken from your belongings.',
    'After a wild night of passion with a client, you wake up to find {coins} missing from your purse.',
    'You engage in a risky encounter with a stranger, only to discover that {coins} have been stolen from your wallet.',
    'During a steamy threesome, your partner steals {coins} from your nightstand when you\'re not looking.',
    'In a moment of weakness, you engage in a forbidden affair, resulting in the theft of {coins} from your pocket.',
    'After a seductive encounter, you realize that {coins} have mysteriously disappeared from your bag.',
    'During an intense BDSM session, your partner swindles {coins} from your wallet while you\'re restrained.',
    'In a moment of desperation, you engage in a risky transaction, only to be robbed of {coins} by your unscrupulous client.',
    'After a wild night of partying, you wake up to find that {coins} have been pickpocketed from your purse.',
    'You naively trust a stranger who promises pleasure in exchange for {coins}, only to be left empty-handed and deceived.',
    'In a moment of weakness, you participate in a group encounter, only to realize that {coins} have been slyly stolen from your possession.',
    'After a passionate rendezvous, you discover that {coins} have been discreetly swiped from your wallet.',
    'During an intimate encounter with a wealthy patron, you find {coins} missing from your purse the next morning.',
    'You engage in a forbidden tryst with a married individual, resulting in the loss of {coins} from your wallet.',
    'After a night of indulgence, you wake up to find {coins} mysteriously gone from your bag.',
    'In a moment of vulnerability, you fall for a scam and lose {coins} to a cunning imposter.',
    'You engage in a steamy affair with a dishonest client who steals {coins} from your pocket while you\'re intimate.',
    'After a wild party, you realize that {coins} have been stolen from your wallet amidst the chaos.',
    'In a moment of desperation, you engage in a risky encounter, only to be robbed of {coins} by a deceptive partner.',
    'After a passionate encounter, you wake up to find that {coins} have been cunningly taken from your purse.',
    'You succumb to the charms of a seductive stranger, only to discover the theft of {coins} from your wallet.',
    'After an exhilarating night of pleasure, you find {coins} missing from your bag, leaving you feeling betrayed.',
    'In a moment of weakness, you engage in a dangerous liaison, resulting in the loss of {coins} from your pocket.',
    'You participate in a high-risk transaction, only to discover that {coins} have been swindled from your possession.',
    'After an intense BDSM session, you realize that {coins} have been silently taken from your wallet.',
    'In a moment of desperation, you engage in a risky encounter, only to be duped out of {coins} by a cunning client.',
    'After a night of debauchery, you wake up to find {coins} mysteriously missing from your purse.',
    'You engage in a forbidden affair, only to discover that {coins} have been cunningly stolen from your wallet.',
    'After a passionate encounter, you realize that {coins} have been discreetly pilfered from your bag.',
    'In a moment of vulnerability, you fall for a scam and lose {coins} to a manipulative imposter.',
    'You engage in a steamy encounter with a dishonest client who swipes {coins} from your pocket while you\'re intimate.',
    'After a steamy encounter with a client, you realize that {coins} have gone missing from your purse.',
    'You engage in a wild night of passion with a stranger, only to wake up and find that {coins} have been stolen from your wallet.',
    'In a moment of lust, you have a risky encounter with a wealthy patron, resulting in the loss of {coins} from your stash.',
    'After a seductive rendezvous, you discover that {coins} have mysteriously disappeared from your account.',
    'You succumb to temptation and engage in a forbidden tryst, only to realize that {coins} have been swindled from your possession.',
    'In a moment of weakness, you have an affair with a married individual, leading to the theft of {coins} from your earnings.',
    'After a night of pleasure, you wake up to find that {coins} have been cunningly taken from your pockets.',
    'You participate in a raunchy escapade, unaware that {coins} have vanished from your secret stash.',
    'In a moment of desire, you engage in a risky encounter that results in the loss of {coins} from your wallet.',
    'After a steamy encounter with a client, you discover that {coins} have been deceitfully pilfered from your savings.',
    'You surrender to temptation and engage in a forbidden affair, only to realize that {coins} have been cunningly swiped from your possession.',
    'In a passionate encounter, you are seduced by a cunning individual who steals {coins} from your earnings.',
    'After a night of wild pleasure, you wake up to find that {coins} have been mysteriously snatched from your pockets.',
    'You participate in a steamy tryst, unaware that {coins} have vanished from your carefully hidden stash.',
    'In a moment of weakness, you have an affair with a manipulative person, leading to the theft of {coins} from your hard-earned savings.',
    'After a night of intense pleasure, you wake up to find that {coins} have been slyly taken from your wallet.',
    'You engage in a seductive escapade, only to discover that {coins} have been artfully pilfered from your secret stash.',
    'In a moment of desire, you give in to a risky encounter that results in the loss of {coins} from your earnings.',
    'After a steamy encounter with a client, you realize that {coins} have been deceitfully swindled from your savings.',
    'You succumb to temptation and engage in a forbidden tryst, only to find that {coins} have been cunningly stolen from your possession.',
    'In a moment of weakness, you have an affair with a married individual, resulting in the theft of {coins} from your wallet.',
    'After a night of pleasure, you wake up to find that {coins} have been cunningly taken from your pockets.',
    'You participate in a raunchy escapade, unaware that {coins} have vanished from your secret stash.',
    'In a moment of desire, you engage in a risky encounter that leads to the loss of {coins} from your earnings.',
    'After a steamy encounter with a client, you discover that {coins} have been deceitfully pilfered from your savings.',
    'You surrender to temptation and engage in a forbidden affair, only to realize that {coins} have been cunningly swiped from your possession.',
    'In a passionate encounter, you are seduced by a cunning individual who steals {coins} from your earnings.',
    'After a night of wild pleasure, you wake up to find that {coins} have been mysteriously snatched from your pockets.',
]

POSITIVE_REPLIES = [
    'Sure.',
    'Of course.',
    'As you wish.',
    'Absolutely.',
    'Can do!',
    'No problem.',
    'I got you.',
    'Okay.',
    'Sure thing!',
    'Aye aye, cap\'n!',
    'ROGER THAT!',
    'I think I can manage that.',
    'I\'m on it.',
    'You\'re the boss.',
    'Alright.',
    'Consider it done.',
    'I\'ll make it happen.',
    'I\'ll get right on it.',
    'I\'ll do my best.',
    'Yep.'
]


def positive_reply() -> str:
    return random.choice(POSITIVE_REPLIES)


NEGATIVE_REPLIES = [
    'Noooooo!!',
    'Nope.',
    'I\'m sorry Dave, I\'m afraid I can\'t do that.',
    'Sir, I\'m afraid I can\'t do that.',
    'I don\'t think so.',
    'Not gonna happen.',
    'Out of the question.',
    'Huh? No.',
    'Nah.',
    'Naw.',
    'What are you, crazy?',
    'Not likely.',
    'Most likely not.',
    'Not in a million years.',
    'Fat chance.',
    'Certainly not.',
    'NEGATORY.',
    'Nuh-uh.',
    'Not in my house!',
    'No way, José.',
    'Not a chance.',
    'Definitely not.'
]


def negative_reply() -> str:
    return random.choice(NEGATIVE_REPLIES)


ERROR_REPLIES = [
    "Please don't do that.",
    "You have to stop.",
    "Do you mind?",
    "In the future, don't do that.",
    "That was a mistake.",
    "You blew it.",
    "You're bad at computers.",
    "Are you trying to kill me?",
    "Noooooo!!",
    "I can't believe you've done this",
]


def error_reply() -> str:
    return random.choice(ERROR_REPLIES)
