"""Pure economy logic split by domain (no ``discord`` imports anywhere).

- :mod:`~app.services.economy.core` — dailies, weekly/monthly, shop pricing,
  loot tables, item effects, lottery draws, prestige math.
- :mod:`~app.services.economy.jobs` — the career ladder behind ``work``/``job``.
- :mod:`~app.services.economy.activities` — ``beg``/``dig``/``search`` tables.
- :mod:`~app.services.economy.pets` — pet species, hunger and passive earnings.
- :mod:`~app.services.economy.quests` — deterministic daily quest boards.
- :mod:`~app.services.economy.achievements` — milestone badges.

Everything is re-exported here so callers keep importing from
``app.services.economy`` directly.
"""

from app.services.economy.achievements import (
    ACHIEVEMENTS,
    Achievement,
    EconomySnapshot,
    evaluate_achievements,
    get_achievement,
)
from app.services.economy.activities import (
    BEG_COOLDOWN,
    BEG_DONORS,
    BEG_FAIL_LINES,
    BEG_SUCCESS_LINES,
    BEG_TABLE,
    DIG_COOLDOWN,
    DIG_TABLE,
    SEARCH_COOLDOWN,
    SEARCH_LOCATIONS,
    SearchLocation,
    SearchOutcome,
    pick_search_options,
    resolve_search,
)
from app.services.economy.core import (
    BOOST_MAX_DURATION_MINUTES,
    BOOST_MAX_PERCENT,
    DAILY_BASE,
    DAILY_COOLDOWN,
    DAILY_RESET,
    DAILY_STREAK_BONUS,
    DAILY_STREAK_CAP,
    FISHING_COOLDOWN,
    FISHING_TABLE,
    HUNTING_COOLDOWN,
    HUNTING_TABLE,
    ITEM_EFFECTS,
    LOOTBOX_BANDS,
    MONTHLY_AMOUNT,
    MONTHLY_COOLDOWN,
    PRESTIGE_BASE_REQUIREMENT,
    PRESTIGE_MAX_LEVEL,
    PRESTIGE_STEP,
    SELL_RATE,
    WEEKLY_AMOUNT,
    WEEKLY_COOLDOWN,
    Catch,
    DailyResult,
    GuildEconomySettings,
    LootEntry,
    PeriodicResult,
    boost_multiplier,
    compute_daily,
    compute_periodic,
    describe_effect,
    pick_weighted_winner,
    prestige_multiplier,
    prestige_requirement,
    roll_loot,
    roll_lootbox,
    sell_price,
    validate_item_effect,
)
from app.services.economy.jobs import (
    JOB_LADDER,
    SHIFT_EVENTS,
    WORK_COOLDOWN,
    Job,
    ShiftEvent,
    ShiftResult,
    available_jobs,
    compute_shift,
    get_job,
    next_unlock,
)
from app.services.economy.pets import (
    HUNGRY_AFTER_HOURS,
    PET_SPECIES,
    STARVING_AFTER_HOURS,
    HungerState,
    PetClaim,
    PetSpecies,
    compute_pet_claim,
    get_species,
    hunger_state,
)
from app.services.economy.quests import (
    DAILY_QUEST_COUNT,
    QUEST_POOL,
    Quest,
    QuestSpec,
    generate_daily_quests,
)

__all__ = (
    'ACHIEVEMENTS',
    'BEG_COOLDOWN',
    'BEG_DONORS',
    'BEG_FAIL_LINES',
    'BEG_SUCCESS_LINES',
    'BEG_TABLE',
    'BOOST_MAX_DURATION_MINUTES',
    'BOOST_MAX_PERCENT',
    'DAILY_BASE',
    'DAILY_COOLDOWN',
    'DAILY_QUEST_COUNT',
    'DAILY_RESET',
    'DAILY_STREAK_BONUS',
    'DAILY_STREAK_CAP',
    'DIG_COOLDOWN',
    'DIG_TABLE',
    'FISHING_COOLDOWN',
    'FISHING_TABLE',
    'HUNGRY_AFTER_HOURS',
    'HUNTING_COOLDOWN',
    'HUNTING_TABLE',
    'ITEM_EFFECTS',
    'JOB_LADDER',
    'LOOTBOX_BANDS',
    'MONTHLY_AMOUNT',
    'MONTHLY_COOLDOWN',
    'PET_SPECIES',
    'PRESTIGE_BASE_REQUIREMENT',
    'PRESTIGE_MAX_LEVEL',
    'PRESTIGE_STEP',
    'QUEST_POOL',
    'SEARCH_COOLDOWN',
    'SEARCH_LOCATIONS',
    'SELL_RATE',
    'SHIFT_EVENTS',
    'STARVING_AFTER_HOURS',
    'WEEKLY_AMOUNT',
    'WEEKLY_COOLDOWN',
    'WORK_COOLDOWN',
    'Achievement',
    'Catch',
    'DailyResult',
    'EconomySnapshot',
    'GuildEconomySettings',
    'HungerState',
    'Job',
    'LootEntry',
    'PeriodicResult',
    'PetClaim',
    'PetSpecies',
    'Quest',
    'QuestSpec',
    'SearchLocation',
    'SearchOutcome',
    'ShiftEvent',
    'ShiftResult',
    'available_jobs',
    'boost_multiplier',
    'compute_daily',
    'compute_periodic',
    'compute_pet_claim',
    'compute_shift',
    'describe_effect',
    'evaluate_achievements',
    'generate_daily_quests',
    'get_achievement',
    'get_job',
    'get_species',
    'hunger_state',
    'next_unlock',
    'pick_search_options',
    'pick_weighted_winner',
    'prestige_multiplier',
    'prestige_requirement',
    'resolve_search',
    'roll_loot',
    'roll_lootbox',
    'sell_price',
    'validate_item_effect',
)
